//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksExamples
{
    using System;
    using System.Collections.Generic;
   using System.Collections.ObjectModel;
    
    public partial class Author
    {
        public Author()
        {
            this.Titles = new ObservableCollection<Title>();
        }
    
        public int AuthorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ObservableCollection<Title> Titles { get; set; }
    }
}
