//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch24ShoppingCartMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.LineItems = new HashSet<LineItem>();
        }
    
        public string ProductID { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string CategoryID { get; set; }
        public string ImageFile { get; set; }
        public decimal UnitPrice { get; set; }
        public int OnHand { get; set; }
    
        public virtual ICollection<LineItem> LineItems { get; set; }
    }
}
